services:
  mall-admin-web:
    build: .
    container_name: mall-admin-web
    restart: always
    ports:
      - "8090:8090"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    # 健康检查
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "-", "http://localhost:8090" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
